spring:
  data:
    mongodb:
      database: library
      port: 27017
      host: localhost

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    initialization-mode: always

  batch:
    job:
      enabled: false
    initialize-schema: always

logging:
  level:
    root: info
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss}%t %-5level : %t %msg%n'
  file: 'applog/app.log'

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - health
          - logfile
          - hystrix.stream
