DROP TABLE IF EXISTS AUTHOR CASCADE;
DROP TABLE IF EXISTS GENRE CASCADE;
DROP TABLE IF EXISTS BOOK CASCADE;

CREATE TABLE GENRE (
id SERIAL PRIMARY KEY,
GENRE varchar(100) NOT NULL);

CREATE TABLE BOOK (
id SERIAL PRIMARY KEY,
ID_GENRE BIGINT REFERENCES GENRE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
TITLE varchar(255) NOT NULL);

CREATE TABLE AUTHOR (
id SERIAL PRIMARY KEY,
ID_BOOK BIGINT REFERENCES BOOK (ID) ON DELETE CASCADE ON UPDATE CASCADE,
SURNAME varchar(50) NOT NULL,
NAME varchar(50) NOT NULL);

commit;