DROP TABLE IF EXISTS AUTHOR CASCADE;
DROP TABLE IF EXISTS GENRE CASCADE;
DROP TABLE IF EXISTS BOOK CASCADE;
DROP TABLE IF EXISTS BOOK_AUTHOR CASCADE;

CREATE TABLE GENRE (
id BIGSERIAL PRIMARY KEY,
GENRE varchar(100) NOT NULL);

CREATE TABLE BOOK (
id BIGSERIAL PRIMARY KEY,
ID_GENRE BIGINT REFERENCES GENRE (ID) ON DELETE CASCADE ON UPDATE CASCADE,
TITLE varchar(255) NOT NULL);

CREATE TABLE AUTHOR (
id BIGSERIAL PRIMARY KEY,
SURNAME varchar(50) NOT NULL,
NAME varchar(50) NOT NULL);

CREATE TABLE BOOK_AUTHOR (
ID_BOOK BIGINT REFERENCES BOOK (id) ON DELETE CASCADE ON UPDATE CASCADE,
ID_AUTHOR  BIGINT REFERENCES AUTHOR (id) ON DELETE CASCADE ON UPDATE CASCADE);

COMMIT;